package com.contabook.Repository.dbaquamovil;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.contabook.Model.dbaquamovil.TblDctos;
import com.contabook.Projection.TblDctosDTO;


@Repository
public interface TblDctosRepo extends JpaRepository<TblDctos, Integer> {
	
	@Query(value = "       SELECT 11 AS idTipoNegocio,                                                              "
	         + "       tblDctos.idDcto    AS idDcto,                                                            "
	         + "       MAX(tblDctosPeriodo.fechaFinal) AS fechaDcto,                                            "
	         + "       'COP' AS  siglaMoneda,                                                                   "
	         + "       tmpCAT.cuentaContableCredito AS idSubcuenta,                                             "
	         + "       MAX(tblTerceros.CC_Nit) AS idCliente, 	                                                "
	         + "       0.0 AS vrDebito,  		                                                                "
	         + "        ROUND(SUM(tblDctosOrdenesDetalle.cantidad * vrVentaUnitario),2)  AS vrCredito,          "        
	         + "        MAX(tblDctos.nombreTercero) AS observacion,                                             "
	         + "        '' AS textoVacio,                                                                       "
	         + "        MAX(tblTerceros.idRuta) AS idRuta,                                                      "
			 + "		 tblDctos.IDTIPOORDEN AS idTipoOrden,                                                   "
			 + "		 tblDctos.idPeriodo AS idPeriodo				                                        "
	         + "        FROM       tblDctosOrdenesDetalle                                                       "
	         + "        INNER JOIN tblDctos                                                                     "
	         + "        ON tblDctos.idLocal =                                                                   "
	         + "                     tblDctosOrdenesDetalle.IDLOCAL                                             "
	         + "        AND tblDctos.idtipoorden =                                                              "
	         + "                     tblDctosOrdenesDetalle.idtipoorden                                         "
	         + "        AND tblDctos.idorden    =                                                               "
	         + "                     tblDctosOrdenesDetalle.idorden                                             "
	         + "        INNER JOIN tblDctosPeriodo                                                              "
	         + "        ON tblDctos.idLocal = tblDctosPeriodo.IDLOCAL                                           "
	         + "       AND tblDctos.idPeriodo = tblDctosPeriodo.idPeriodo                                       "
	         + "        INNER JOIN                                                                              "
	         + "        (SELECT tblPlus.idLocal,                                                                "
	         + "        tblPlus.idPlu,                                                                          "
	         + "         tblPlus.idTipo,                                                                        "
	         + "       (tblCategorias.nombreCategoria + ' ' +                                                   "
	         + "                  tblPlus.nombrePlu) AS nombrePlu,                                              "
	         + "         tblPlus.cuentaContableCredito                                                          "
	         + "        FROM  tblCategorias                                                                     "
	         + "        INNER JOIN tblPlus                                                                      "
	         + "        ON tblCategorias.idLocal = tblPlus.idLocal                                              "
	         + "        AND tblCategorias.idLinea = tblPlus.idLinea                                             "
	         + "        AND tblCategorias.IdCategoria =                                                         "
	         + "                           tblPlus.idCategoria) AS tmpCAT                                       "
	         + "       ON tmpCAT.idLocal = tblDctosOrdenesDetalle.idLocal                                       "
	         + "        AND tmpCAT.idPlu  = tblDctosOrdenesDetalle.idPlu                                        "
	         + "      INNER JOIN tblTerceros                                                                    "
	         + "        ON tblTerceros.idLocal = tblDctos.idLocal                                               "
	         + "        AND tblTerceros.idCliente  = tblDctos.idCliente                                         "
	         + "        WHERE tblDctos.idLocal   =                                                              "
	         + "     ?1                                                                                         "
	         + "        AND tblDctos.idTipoOrden IN (9 , 29)                                                    "
	         + "        AND tblDctos.idPeriodo   =                                                              "
	         + "     ?2                                                                                         "
	         + "        AND (tblDctosOrdenesDetalle.cantidad *                                                  "
	         + "                              vrVentaUnitario) != 0                                             "
	         + "        AND tmpCAT.idTipo < 100                                                                 "
	         + "        GROUP BY tblDctosOrdenesDetalle.idLocal,                                                "
	         + "        	 tmpCAT.cuentaContableCredito,                                                      "
	         + "                tblDctos.idDcto,		   	                                                    "
	         + "                tblDctos.idCliente,                                                             "
			 + "				 tblDctos.IDTIPOORDEN,                                                          "
			 + "				 tblDctos.idPeriodo                                                             "
	         + "        HAVING SUM(tblDctosOrdenesDetalle.cantidad *                                            "
	         + "                                   vrVentaUnitario) > 0                                         "
	         + "        UNION 					                                                                "
	         + "        SELECT 11 AS tipoComprobante,                                                           "
	         + "       tblDctos.idDcto    AS conscutivoComprobante,                                             "
	         + "       MAX(tblDctosPeriodo.fechaFinal) AS fechaElaboracion,                                     "
	         + "       'COP' AS  SiglaMoneda,                                                                   "
	         + "       tmpCAT.cuentaContableCredito  AS codCuentaContable,                                      "
	         + "       MAX(tblTerceros.CC_Nit) AS idCliente, 	                                                "
	         + "       ROUND(SUM(tblDctosOrdenesDetalle.cantidad *  vrVentaUnitario),2) * (-1.0) AS debito,     "       
	         + "        0.0 AS credito,  				                                                        "
	         + "        MAX(tblDctos.nombreTercero) AS observacion,                                             "
	         + "        '' AS textoVacio,                                                                       "
	         + "        MAX(tblTerceros.idRuta) AS idRuta,                                                      "
			 + "		 tblDctos.IDTIPOORDEN,                                                                  "
			 + "		 tblDctos.idPeriodo                                                                     "
	         + "        FROM       tblDctosOrdenesDetalle                                                       "
	         + "        INNER JOIN tblDctos                                                                     "
	         + "        ON tblDctos.idLocal =                                                                   "
	         + "                      tblDctosOrdenesDetalle.IDLOCAL                                            "
	         + "        AND tblDctos.idtipoorden =                                                              "
	         + "                      tblDctosOrdenesDetalle.idtipoorden                                        "
	         + "        AND tblDctos.idorden    =                                                               "
	         + "                      tblDctosOrdenesDetalle.idorden                                            "
	         + "        INNER JOIN tblDctosPeriodo                                                              "
	         + "        ON tblDctos.idLocal = tblDctosPeriodo.IDLOCAL                                           "
	         + "        AND tblDctos.idPeriodo = tblDctosPeriodo.idPeriodo                                      "
	         + "        INNER JOIN                                                                              "
	         + "        (SELECT tblPlus.idLocal,                                                                "
	         + "                tblPlus.idPlu,                                                                  "
	         + "        	    tblPlus.idTipo,                                                                 "
	         + "               (tblCategorias.nombreCategoria + ' ' +                                           "
	         + "                          tblPlus.nombrePlu) AS nombrePlu,                                      "
	         + "        	    tblPlus.cuentaContableCredito                                                   "
	         + "        FROM  tblCategorias                                                                     "
	         + "        INNER JOIN tblPlus                                                                      "
	         + "        ON tblCategorias.idLocal = tblPlus.idLocal                                              "
	         + "        AND tblCategorias.idLinea = tblPlus.idLinea                                             "
	         + "        AND tblCategorias.IdCategoria =                                                         "
	         + "                           tblPlus.idCategoria) AS tmpCAT                                       "
	         + "        ON tmpCAT.idLocal = tblDctosOrdenesDetalle.idLocal                                      "
	         + "        AND tmpCAT.idPlu  = tblDctosOrdenesDetalle.idPlu                                        "
	         + "        INNER JOIN tblTerceros                                                                  "
	         + "        ON tblTerceros.idLocal = tblDctos.idLocal                                               "
	         + "        AND tblTerceros.idCliente  = tblDctos.idCliente                                         "
	         + "        WHERE tblDctos.idLocal   =                                                              "
	         + "     ?1                                                                                         "
	         + "        AND tblDctos.idTipoOrden IN (9 , 29)                                                    "
	         + "        AND tblDctos.idPeriodo   =                                                              "
	         + "     ?2                                                                                         "
	         + "        AND (tblDctosOrdenesDetalle.cantidad *                                                  "
	         + "                              vrVentaUnitario) != 0                                             "
	         + "        AND tmpCAT.idTipo < 100                                                                 "
	         + "        GROUP BY tblDctosOrdenesDetalle.idLocal,                                                "
	         + "        	 tmpCAT.cuentaContableCredito,                                                      "
	         + "                tblDctos.idDcto,		   	                                                    "
	         + "                tblDctos.idCliente,                                                             "
			 + "				 tblDctos.IDTIPOORDEN,                                                          "
			 + "				 tblDctos.idPeriodo                                                             "
	         + "        HAVING SUM(tblDctosOrdenesDetalle.cantidad *                                            "
	         + "                                   vrVentaUnitario) < 0                                         "
	         + "        UNION                                                                                   "
	         + "        SELECT 11 AS tipoComprobante,                                                           "
	         + "        tblDctos.idDcto    AS conscutivoComprobante,                                            "
	         + "        MAX(tblDctosPeriodo.fechaFinal) AS fechaElaboracion,                                    "
	         + "        'COP' AS  SiglaMoneda,                                                                  "
	         + "        tmpCAT.cuentaContableDebito  AS codCuentaContable,                                      "
	         + "        MAX(tblTerceros.CC_Nit) AS idCliente, 	                                                "
	         + "        ROUND(SUM(tblDctosOrdenesDetalle.cantidad *  vrVentaUnitario),2)  AS debito,            "       
	         + "        0.0 AS credito,                                                                         "
	         + "        MAX(tblDctos.nombreTercero) AS observacion,                                             "
	         + "        '' AS textoVacio,                                                                       "
	         + "        MAX(tblTerceros.idRuta) AS idRuta,                                                      "
			 + "		 tblDctos.IDTIPOORDEN,                                                                  "
			 + "		 tblDctos.idPeriodo                                                                     "
	         + "        FROM       tblDctosOrdenesDetalle                                                       "
	         + "        INNER JOIN tblDctos                                                                     "
	         + "        ON tblDctos.idLocal =                                                                   "
	         + "                       tblDctosOrdenesDetalle.IDLOCAL                                           "
	         + "        AND tblDctos.idtipoorden =                                                              "
	         + "                      tblDctosOrdenesDetalle.idtipoorden                                        "
	         + "        AND tblDctos.idorden    =                                                               "
	         + "                      tblDctosOrdenesDetalle.idorden                                            "
	         + "        INNER JOIN tblDctosPeriodo                                                              "
	         + "        ON tblDctos.idLocal = tblDctosPeriodo.IDLOCAL                                           "
	         + "        AND tblDctos.idPeriodo = tblDctosPeriodo.idPeriodo                                      "
	         + "        INNER JOIN                                                                              "
	         + "        (SELECT tblPlus.idLocal,                                                                "
	         + "        tblPlus.idPlu,                                                                          "
	         + "         tblPlus.idTipo,                                                                        "
	         + "       (tblCategorias.nombreCategoria + ' ' +                                                   "
	         + "        tblPlus.nombrePlu) AS nombrePlu,                                                        "
	         + "         tblPlus.cuentaContableDebito                                                           "
	         + "        FROM  tblCategorias                                                                     "
	         + "        INNER JOIN tblPlus                                                                      "
	         + "        ON tblCategorias.idLocal = tblPlus.idLocal                                              "
	         + "        AND tblCategorias.idLinea = tblPlus.idLinea                                             "
	         + "        AND tblCategorias.IdCategoria =                                                         "
	         + "                       tblPlus.idCategoria) AS tmpCAT                                           "
	         + "       ON tmpCAT.idLocal = tblDctosOrdenesDetalle.idLocal                                       "
	         + "        AND tmpCAT.idPlu  = tblDctosOrdenesDetalle.idPlu                                        "
	         + "      INNER JOIN tblTerceros                                                                    "
	         + "        ON tblTerceros.idLocal = tblDctos.idLocal                                               "
	         + "        AND tblTerceros.idCliente  = tblDctos.idCliente                                         "
	         + "        WHERE tblDctos.idLocal   =                                                              "
	         + "     ?1                                                                                         "
	         + "        AND tblDctos.idTipoOrden IN (9 , 29)                                                    "
	         + "        AND tblDctos.idPeriodo   =                                                              "
	         + "     ?2                                                                                         "
	         + "        AND (tblDctosOrdenesDetalle.cantidad *                                                  "
	         + "                              vrVentaUnitario) != 0                                             "
	         + "        AND tmpCAT.idTipo < 100                                                                 "
	         + "        GROUP BY tblDctosOrdenesDetalle.idLocal,                                                "
	         + "        	 tmpCAT.cuentaContableDebito,                                                       "
	         + "                tblDctos.idDcto,		   	                                                    "
	         + "                tblDctos.idCliente,                                                             "
			 + "				 tblDctos.IDTIPOORDEN,                                                          "
			 + "				 tblDctos.idPeriodo                                                             "
	         + "        HAVING SUM(tblDctosOrdenesDetalle.cantidad *                                            "
	         + "                         vrVentaUnitario) > 0                                                   "
	         + "        UNION    				                                                                "
	         + "        SELECT 11 AS tipoComprobante,                                                           "
	         + "       tblDctos.idDcto    AS conscutivoComprobante,                                             "
	         + "        MAX(tblDctosPeriodo.fechaFinal) AS fechaElaboracion,                                    "
	         + "       'COP' AS  SiglaMoneda,                                                                   "
	         + "        tmpCAT.cuentaContableDebito  AS codCuentaContable,                                      "
	         + "       MAX(tblTerceros.CC_Nit) AS idCliente, 	                                                "
	         + "       0 AS debito,        		                                                                "
	         + "       ROUND(SUM(tblDctosOrdenesDetalle.cantidad *  vrVentaUnitario),2) * (-1.0) AS  credito,   "        
	         + "        MAX(tblDctos.nombreTercero) AS observacion,                                             "
	         + "        '' AS textoVacio,                                                                       "
	         + "        MAX(tblTerceros.idRuta) AS idRuta,                                                      "
			 + "		 tblDctos.IDTIPOORDEN,                                                                  "
			 + "		 tblDctos.idPeriodo                                                                     "
	         + "        FROM       tblDctosOrdenesDetalle                                                       "
	         + "        INNER JOIN tblDctos                                                                     "
	         + "        ON tblDctos.idLocal =                                                                   "
	         + "                            tblDctosOrdenesDetalle.IDLOCAL                                      "
	         + "        AND tblDctos.idtipoorden =                                                              "
	         + "                        tblDctosOrdenesDetalle.idtipoorden                                      "
	         + "        AND tblDctos.idorden    =                                                               "
	         + "                            tblDctosOrdenesDetalle.idorden                                      "
	         + "        INNER JOIN tblDctosPeriodo                                                              "
	         + "        ON tblDctos.idLocal = tblDctosPeriodo.IDLOCAL                                           "
	         + "        AND tblDctos.idPeriodo = tblDctosPeriodo.idPeriodo                                      "
	         + "        INNER JOIN                                                                              "
	         + "        (SELECT tblPlus.idLocal,                                                                "
	         + "        tblPlus.idPlu,                                                                          "
	         + "         tblPlus.idTipo,                                                                        "
	         + "       (tblCategorias.nombreCategoria + ' ' +                                                   "
	         + "        tblPlus.nombrePlu) AS nombrePlu,                                                        "
	         + "         tblPlus.cuentaContableDebito                                                           "
	         + "        FROM  tblCategorias                                                                     "
	         + "        INNER JOIN tblPlus                                                                      "
	         + "        ON tblCategorias.idLocal = tblPlus.idLocal                                              "
	         + "        AND tblCategorias.idLinea = tblPlus.idLinea                                             "
	         + "        AND tblCategorias.IdCategoria =                                                         "
	         + "                           tblPlus.idCategoria) AS tmpCAT                                       "
	         + "       ON tmpCAT.idLocal = tblDctosOrdenesDetalle.idLocal                                       "
	         + "        AND tmpCAT.idPlu  = tblDctosOrdenesDetalle.idPlu                                        "
	         + "      INNER JOIN tblTerceros                                                                    "
	         + "        ON tblTerceros.idLocal = tblDctos.idLocal                                               "
	         + "        AND tblTerceros.idCliente  = tblDctos.idCliente                                         "
	         + "        WHERE tblDctos.idLocal   =                                                              "
	         + "     ?1                                                                                         "
	         + "        AND tblDctos.idTipoOrden IN (9 , 29)                                                    "
	         + "        AND tblDctos.idPeriodo   =                                                              "
	         + "     ?2                                                                                         "
	         + "        AND (tblDctosOrdenesDetalle.cantidad *                                                  "
	         + "                              vrVentaUnitario) != 0                                             "
	         + "        AND tmpCAT.idTipo < 100                                                                 "
	         + "        GROUP BY tblDctosOrdenesDetalle.idLocal,                                                "
	         + "        	 tmpCAT.cuentaContableDebito,                                                       "
	         + "                tblDctos.idDcto,		   	                                                    "
	         + "                tblDctos.idCliente,                                                             "
			 + "				 tblDctos.IDTIPOORDEN,                                                          "
			 + "				 tblDctos.idPeriodo                                                             "
	         + "        HAVING SUM(tblDctosOrdenesDetalle.cantidad *                                            "
	         + "                  vrVentaUnitario) < 0                                                          "
	         + "      	     ORDER BY 1,2,6,7 DESC                                                              ",
            nativeQuery = true)
	  List<TblDctosDTO> listaComprobanteDetallado(int idLocal, int idPeriodo);

}
