package com.contabook.Repository.dbaquamovil;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.contabook.Model.dbaquamovil.TblPagos;
import com.contabook.Projection.TblPagosDTO;

@Repository
public interface TblPagosRepo extends JpaRepository<TblPagos, Integer> {
	
	@Query(value = " SELECT tblpagos.nitCC AS idCliente,       "
            + "        tblterceros.nombreTercero,         "
            + "        tblpagos.idLocal,                  "
            + "        tblpagos.idTipoOrden,              "
            + "        tblpagos.idRecibo,                 "
            + "        tblpagos.indicador,                "
            + "        tblpagos.fechaPago,                "
            + "        tmpMED.vrMedio AS vrPago,          "
            + "        tblpagos.vrRteFuente,              "
            + "        tblpagos.vrDescuento,              "
            + "        tblpagos.vrRteIva,                 "
            + "        tblpagos.idDcto,                   "
            + "        tblpagos.nitCC,              "
            + "        tblpagos.idPlanilla,               "
            + "        tblpagos.vrRteIca,                 "
            + "        tbltercerosruta.nombreCiclo        "
            + "                            + ' / ' +      "
            + "        tbltercerosruta.nombreRuta         "
            + "                           AS nombreRuta,  "
            + "        tblterceroestracto.nombreEstracto, "
            + "        tblpagos.idPeriodo,                "
            + "        ctrlusuarios.nombreUsuario         "
            + "                        AS aliasUsuario,   "
            + "        tmpMED.idMedio,                    "
            + "        tblmediospago.nombreMedio,         "
            + "        tblTerceros.CC_Nit                 "
            + " FROM tblpagos                             "
            + " INNER JOIN tblterceros                    "
            + " ON tblpagos.idLocal = tblterceros.idLocal "
            + " AND tblpagos.nitCC =                      "
            + "                     tblterceros.idCliente "
            + " INNER JOIN tblterceroestracto             "
            + " ON tblterceros.idLocal     =              "
            + "               tblterceroestracto.idLocal  "
            + " AND tblterceros.idEstracto =              "
            + "            tblterceroestracto.idEstracto  "
            + " INNER JOIN tbltercerosruta                "
            + " ON tblterceros.idLocal  =                 "
            + "                   tbltercerosruta.idLocal "
            + " AND tblterceros.idRuta     =              "
            + "                    tbltercerosruta.idRuta "
            + " INNER JOIN ctrlusuarios                   "
            + " ON tblpagos.idLocal =                     "
            + "                      ctrlusuarios.idLocal "
            + " AND tblpagos.idUsuario =                  "
            + "                  ctrlusuarios.idUsuario   "
            + " INNER JOIN			              "
            + " ( SELECT  idLocal                         "
            + "       ,idTipoOrden                        "
            + "       ,idRecibo                           "
            + "       ,indicador                          "
            + "       ,idMedio                            "
            + "       ,SUM(vrMedio) AS vrMedio            "
            + "   FROM tblpagosmedios                     "
            + "   WHERE idLocal =                         "
            + "?1                             "
            + "   AND idTipoOrden = 9                     "
            + "   GROUP BY  idLocal                       "
            + "       ,idTipoOrden                        "
            + "       ,idRecibo                           "
            + "       ,indicador                          "
            + " 	  ,idMedio ) AS tmpMED                "
            + " ON tmpMED.idLocal =  tblpagos.idLocal     "
            + " AND tmpMED.idTipoOrden =                  "
            + "                      tblpagos.idTipoOrden "
            + " AND tmpMED.idRecibo = tblpagos.idRecibo   "
            + " AND tmpMED.indicador = tblpagos.indicador "
            + " INNER JOIN tblmediospago                  "
            + " ON tblmediospago.idMedio = tmpMED.idMedio "
            + " AND	tblmediospago.idLocal = tmpMED.idLocal "
            + " WHERE  tblpagos.idLocal   =        "
            + "?1                      "
            + " AND  tblpagos.idTipoOrden = 9      "
            + " AND (tblpagos.indicador            "
            + "               BETWEEN 1 AND 2)     "
            + " AND  tblpagos.idPeriodo   =        "
            + "?2                    "
            + " ORDER BY tmpMED.idMedio,           "
            + "          tblpagos.fechaPago,       "
            + "          tblpagos.idRecibo ", nativeQuery = true)
	  List<TblPagosDTO> listaRepRecaudoPeriodo(int idLocal, int idPeriodo);

}
